name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: chelseachen007/ObPublish
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
          # 把子模块打开
          submodules: 'true'

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "aqwejie@qq.com"
          git config user.name "chelseachen007"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
